apiVersion: batch/v1
kind: CronJob
metadata:
  name: pyzn-cron
  labels:
    app: pyzn
spec:
  schedule: "00 02 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: google-cloud-key
              secret:
                secretName: service-account-credentials
            - name: newrelic-config
              secret:
                secretName: newrelic-config
          containers:
            - name: pyzn
              image: ghcr.io/khulnasoft/pyzn
              env:
                - name: APPLICATION_ENV
                  value: prod
                - name: PYZN_LOGGING_FILE
                  value: app.log
                - name: PYZN_BIGQUERY_CREDENTIALS
                  value: /var/secrets/google/bq_credentials.json
                - name: NEW_RELIC_CONFIG_FILE
                  value: /var/secrets/newrelic/newrelic.ini
                - name: PYZN_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pyzn-secrets
                      key: admin-password
                      optional: false
              ports:
                - containerPort: 8080
              imagePullPolicy: Always
              command: ["/bin/sh"]
              args:
                - -c
                - >-
                    newrelic-admin run-program python -m pyzn import:downloads:day &&
                    curl -fsS --retry 3 https://hc-ping.com/b5fb64db-877f-469c-9535-311e2e658b9f
              volumeMounts:
                - name: google-cloud-key
                  mountPath: /var/secrets/google
                - name: newrelic-config
                  mountPath: /var/secrets/newrelic
              resources:
                requests:
                  memory: "100Mi"
                  cpu: "150m"
                limits:
                  memory: "150Mi"
                  cpu: "200m"
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: dockerconfigjson-github-com