services:
  pyzn:
    image: ghcr.io/khulnasoft/pyzn:${PYZN_VERSION}
    environment:
      - APPLICATION_ENV=dev
      - FLASK_DEBUG=1
      - SHELL=/bin/bash
    ports:
      - 5200:8080
    volumes:
      - ./:/code
    links:
      - mongodb:mongodb
    command: "gunicorn -c /code/infrastructure/dockerfiles/pyzn/gunicorn.conf.py pyzn.infrastructure.web.__init__:app"

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/datadb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pyzn
      - MONGO_INITDB_ROOT_PASSWORD=pyzn

  pyzn-test:
    image: ghcr.io/khulnasoft/pyzn-test:${PYZN_VERSION}
    environment:
      - APPLICATION_ENV=tests
      - FLASK_DEBUG=1
      - SHELL=/bin/bash
    volumes:
      - ./:/code
    links:
      - mongodb:mongodb
    command: sleep infinity

volumes:
  mongodb_data: {}
