name: CI and CD

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build pyzn image
        run: docker build --file infrastructure/dockerfiles/pyzn/Dockerfile --tag ghcr.io/khulnasoft/pyzn:latest .
      - name: Push image
        run: docker push ghcr.io/khulnasoft/pyzn:latest
      - name: Build pyzn-test image
        run: docker build --file infrastructure/dockerfiles/pyzn-test/Dockerfile --tag ghcr.io/khulnasoft/pyzn-test:latest .
      - name: Push image
        run: docker push ghcr.io/khulnasoft/pyzn-test:latest
  tests:
    name: Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Start environment
        run: DOCKER_TAG=latest make start-containers
      - name: Run tests
        run: DOCKER_TAG=latest make params=-T tests